### ISSUE TITLE
version.py not importing on Windows.

### ISSUE THREAD

**Issue by pkpp1233** [blockspring/blockspring.py#3]
Looks like this dependency is broken on some machines?

**Comment by jjangsangy** [comment]
Fixed it!

https://github.com/blockspring/blockspring.py/pull/4

Sorry, I introduced this bug by using symlinks.

**Comment by pkpp1233** [comment]
@jtokoph - is this ok to push? It looks like we had another user run into it.

**Comment by pkpp1233** [comment]
Still broken with new fix. I'm just going to hardcode the version for now.
